import { Box, Container, Flex, Heading, Text } from '@chakra-ui/react';
import React from 'react';
import { ContainerHero, Hero } from '../atoms/Hero';

export const RoadmapPage = () => {
  return (
    <>
      <Hero bg="black" color="white" py={12}>
        <Container maxW="container.lg">
          <Flex direction="column" mb={6} gridGap={12}>
            <Heading size="4xl" mb={5} fontWeight="800">
              Roadmap
            </Heading>
            <Box>
              <Heading size="md">Started at EthOnline 2021</Heading>
              <Text>
                At EthGlobal's worldwide hackathon, we refined the concept for
                Splice and developed a working prototype.
              </Text>
            </Box>
            <Box>
              <Heading size="md">ETHOnline Finalists </Heading>
              <Text>
                We made it! Amongst 217 teams we were chosen as one of the 17
                finalists.
              </Text>
            </Box>
            <Box>
              <Heading size="md">Releasing preview at NFT NYC </Heading>
              <Text>
                We're releasing a preview version of Splice in time for the
                conference, that lets you mint a header for your PFP.
              </Text>
            </Box>
            <Box>
              <Heading size="md">Build community</Heading>
              <Text>
                We'll gather a dynamic community to help steer decisions going
                forward.
              </Text>
            </Box>
            <Box>
              <Heading size="md">
                Onboarding creative Generative Artists
              </Heading>
              <Text>
                We'll select generative artists for our curated collections.
              </Text>
            </Box>
            <Box>
              <Heading size="md">Partner with collections</Heading>
              <Text>
                Splice is a platform that strives to establish fair economical
                measures. We foresee to share revenue that's generated by
                minting or selling spliced artwork is shared among collections,
                artists, marketplaces and the protocol itself.
              </Text>
            </Box>
            <Box>
              <Heading size="md">Official Launch (Jan 22)</Heading>
              <Text>
                The official launch will open up the Splice platform for
                community based governance and trustless art curation
              </Text>
            </Box>
            <Box>
              <Heading size="md">Minting for the Metaverse</Heading>
              <Text>
                Splice goes far beyond header images. Imagine virtual swords
                weilded out of scrap metal of old gaming NFTS's armors. Artists
                and collections collaborate on the Splice platform to add value
                to each other's ecosystem without the need of immediate
                cooperation
              </Text>
            </Box>
          </Flex>
        </Container>
      </Hero>

      <ContainerHero bg="white">
        <Flex direction="column" gridGap={5} flex="0">
          <Heading size="xl">What's in for you?</Heading>

          <Heading size="md">Collectors</Heading>
          <Text>
            You're collecting NFTs for a reason. Some may gain value, some are
            useful in games, some follow a roadmap that allow you to use them as
            proof of ownership to mint new ones. With Splice you can create
            additional arts to support the NFTs you already own, eventually
            making them more valuable.
          </Text>
          <Heading size="md">Artists</Heading>
          <Text>
            You're a coder with a mathematical background? The space of
            generative artists is exploding. Getting noticed and paid for
            algorithms needs a platform that puts your work on display. Splice
            is not yet another platform for arbitrary digital artwork, since
            each of our creations has an origin (we call it a heritage). We're
            giving the majority of all splice minting fees and sales royalties
            (85%) to artists who decide to offer users to mint their algorithms
            on Splice.
          </Text>
          <Heading size="md">Collections</Heading>
          <Text>
            While not being part of our preview versions, we're onboarding
            collections to be first class community and shareholder members of
            the Splice ecosystem. As an owner of a collection which Splices will
            be based on you can register beneficiary addresses at our contract
            that will receive an amount of all Splice activity related to your
            tokens.
          </Text>
          <Heading size="lg">Community</Heading>
          <Text>
            As active users you will have an opportunity to get your voice heard
            during the preview, staging and production phases of Splice. We're
            planning to decentralize the protocol's governance completely so
            users who're participating in the planning, development and
            maintenance will have a chance to get a fair share of governance
            incentives that not only entitle them to vote on minting new styles
            but also gain rewards by staking Splice shares into the governance
            protocol.
          </Text>
        </Flex>
      </ContainerHero>

      <ContainerHero bg="gray.100">
        <Flex direction="column" gridGap={5}>
          <Heading size="2xl">Technical Details</Heading>
          <Text>tbd</Text>
        </Flex>
      </ContainerHero>
    </>
  );
};
