site_name: S P L I C E Docs
repo_url: https://github.com/SpliceNFT/splicenft

nav:
  - Home: index.md
  - Users: users.md
  - Developers: developers.md
  - Artists: artists.md
  - FAQs: faqs.md

theme:
  name: material
  palette:
    primary: black
    accent: lime
  features:
    - content.tabs.link
  #    - navigation.tabs
  logo: logo.png

site_dir: _docs
markdown_extensions:
  - tables
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/splicenft
    - icon: fontawesome/brands/github
      link: https://github.com/SpliceNFT/splicenft
