@auth = {{$dotenv COVALENT_AUTH}}
@account = 0x70631b7376f4956185dac1b9cb4e9f83ccbc2764
@coolcats = 0x1a92f7381b9f03921564a437210bb9396471050c




GET https://api.covalenthq.com/v1/4/tokens/{{coolcats}}/nft_metadata/3973/
Authorization: Basic {{auth}}:

###

#GET https://api.covalenthq.com/v1/1/address/0x70631b7376f4956185dac1b9cb4e9f83ccbc2764/balances_v2/?nft=true&no-nft-fetch=true
GET https://api.covalenthq.com/v1/42/address/0xE231B4e55fE1D0Afb3e746e64E78eEffB5b599d1/balances_v2/?nft=true
Authorization: Basic {{auth}}:
#Authorization: token {{auth}}