@auth = {{$dotenv NFTPORT_AUTH}}
@account = 0x70631b7376f4956185dac1b9cb4e9f83ccbc2764
# bored apes 0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d
@coolcats = 0x1a92f7381b9f03921564a437210bb9396471050c
POST https://api.nftport.xyz/visual_search_by_url
Authorization: {{auth}}
Content-Type: application/json

{
  "url": "https://lh3.googleusercontent.com/k-97mLiInpbUdPOxbbCsswbMS60BlJ1hTOxSPl5y_lYDKCL3Xw-rqU9LuOj62m0o3f5-TLRYVgb3Ywh0L-MZxxrugUw84969CA7-H_0=s0"
}

###

POST https://api.nftport.xyz/visual_search
Authorization: {{auth}}
Content-Type: application/json

{
  "query": "cat"
}

###

GET https://api.nftport.xyz/text_search?chain=ethereum&text=cool+cats&page_size=10
Authorization: {{auth}}

###

GET https://api.nftport.xyz/account/{{account}}/nfts?chain=ethereum&page_size=10
Authorization: {{auth}}

###

GET https://api.nftport.xyz/nfts?chain=ethereum&page_size=10
Authorization: {{auth}}

###


GET https://api.nftport.xyz/nfts/{{coolcats}}?chain=ethereum&account_address={{account}}&page_size=10
Authorization: {{auth}}

###

GET https://api.nftport.xyz/nfts/{{coolcats}}/3973?chain=ethereum
Authorization: {{auth}}

###

