[package]
name = "testdecode"
version = "0.1.0"
authors = ["Stefan <stadolf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
anyhow = "1.0"
tiny-keccak = "1.5.0"
hex = "0.4.3"
ethabi = { git = "https://github.com/graphprotocol/ethabi.git", branch = "master" }
hex-literal = "0.2.1"